source "http://rubygems.org"
source "http://gems.github.com"
source "http://gemcutter.org"

gem "bundler"

gem "rails", "2.3.8"
gem "abstract"

gem "akismet"
gem "builder"
gem "configuration"
gem "cssmin"
gem "daemon_controller"
gem "daemons"
gem "erubis"
gem "eventmachine"
gem "fastthread"
gem "file-tail"
gem "hpricot"
gem "innate"
gem "jsmin"
gem "json_pure"
gem "mysql", "2.8.1"
gem "net-flickr"
gem "nokogiri", "1.4.4"
gem "not-naughty"
gem "passenger"
gem "ramaze", "2009.02"
gem "rb-readline", "0.5.0"
gem "RedCloth"
gem "rubytree"
gem "sanitize", "1.2.1"
gem "sequel"
gem "sequel_notnaughty"
gem "guardian-content",  "~> 0.2.2"#:git => "git://github.com/guardian-openplatform/contentapi-ruby.git"
gem "tumblr-api"
gem "thin"
gem "twitter", "4.8.1"

